GET http://localhost:8080/app/hello
Accept: application/json
API_KEY: 6bf64ec5-5eee-4d14-994f-365c929b37fb

###

GET http://localhost:8080/app/bye
API_KEY: YOUR_API_KEY

### without API_KEY
GET http://localhost:8080/app/bye
