version: "3.8"
services:
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  go_rate_limit:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - redis
    env_file:
      - .env