
### CREATE IP RULE
POST http://localhost:8080/admin/ip/ip-rule
Content-Type: application/json

{
  "ip": "123.456.789.012",
  "max_request": 100,
  "expires_in": "10s"
}

### GET BY IP
GET http://localhost:8080/admin/ip/ip-rule/123.456.789.012
Content-Type: application/json
Accept: application/json

### UPDATE BY ID
PUT http://localhost:8080/admin/ip/ip-rule/adf67bd9-f30d-4926-8b67-d3a4c8cd9db5
Content-Type: application/json
Accept: application/json

{
  "ip": "123.456.789.123",
  "max_request": 123,
  "expires_in": "123s"
}

### DELETE BY ID
DELETE http://localhost:8080/admin/ip/ip-rule/adf67bd9-f30d-4926-8b67-d3a4c8cd9db5
Content-Type: application/json
Accept: application/json


