
### CREATE IP RULE
POST http://localhost:8081/admin/ip/ip-rule
Content-Type: application/json

{
  "ip": "192.168.0.213",
  "max_request": 3,
  "expires_in": "10s"
}

### GET ALL

GET http://localhost:8081/admin/ip/ip-rule/all
Content-Type: application/json
Accept: application/json

### GET BY IP
GET http://localhost:8081/admin/ip/ip-rule/123.456.789.013
Content-Type: application/json
Accept: application/json

### UPDATE BY ID
PUT http://localhost:8081/admin/ip/ip-rule/98effa60-25f1-440d-a32a-52c26565a131
Content-Type: application/json
Accept: application/json

{
  "ip": "192.168.0.213",
  "max_request": 3,
  "expires_in": "5s"
}

### DELETE BY ID
DELETE http://localhost:8081/admin/ip/ip-rule/9d1f4814-7de3-4114-95be-289e4b48d6b2
Content-Type: application/json
Accept: application/json


