############# TOKEN

### CREATE token RULE
POST http://localhost:8080/admin/token/token-rule
Content-Type: application/json

{
  "max_request": 20,
  "expires_in": "5s"
}

### GET ALL
GET http://localhost:8080/admin/token/token-rule/all
Content-Type: application/json
Accept: application/json


### GET BY TOKEN
GET http://localhost:8080/admin/token/token-rule/7ed42fa2-6d8b-4faa-9e20-5f4f1fd52c5c
Content-Type: application/json
Accept: application/json

### UPDATE BY ID
PUT http://localhost:8080/admin/token/token-rule/54ce2b9a-4832-441d-8489-c7b9c73cb922
Content-Type: application/json
Accept: application/json

{
  "max_request": 123,
  "expires_in": "123s"
}

### DELETE BY ID
DELETE http://localhost:8080/admin/token/token-rule/960ef811-7830-4be8-92e5-580313282f81
Content-Type: application/json
Accept: application/json

